-- Add research dossier fields to conversations table
-- Migration: 000031_add_research_dossier
-- Created: 2026-01-04

ALTER TABLE conversations
ADD COLUMN research_dossier TEXT,
ADD COLUMN research_dossier_status VARCHAR(20),
ADD COLUMN research_dossier_generated_at BIGINT,
ADD COLUMN research_dossier_error TEXT;

COMMENT ON COLUMN conversations.research_dossier IS 'Comprehensive research dossier generated by Perplexity Deep Research Agent in markdown format';
COMMENT ON COLUMN conversations.research_dossier_status IS 'Status of research generation: null, processing, completed, or failed';
COMMENT ON COLUMN conversations.research_dossier_generated_at IS 'Timestamp when research dossier was successfully generated';
COMMENT ON COLUMN conversations.research_dossier_error IS 'Error message if research generation failed';








